dataset_config:
  detection_coco:
    use_images: true
    zoo_requirements:
    - coco.detection_2017
    data_dir: ${env.data_dir}/datasets
    images:
      train:
      - coco/detection_2017/images/train2017
      val:
      - coco/detection_2017/images/val2017
      test:
      - coco/detection_2017/images/test2017
    annotations:
      train:
      - coco/detection_2017/annotations/annotations/instances_train2017.json
      val:
      - coco/detection_2017/annotations/annotations/instances_val2017.json
      test:
      - coco/detection_2017/annotations/annotations/image_info_test-dev2017.json
    load_attributes: false  # COCO has no attribute annotations
    processors:
      detection_image_and_target_processor:
        type: detr_image_and_target
        params:
          train_image_sizes: [384]
          train_resize_random_sizes: [384]
          train_crop_size: [384, 384]
          test_image_size: 384
          max_size: 384
          fixed_image_size: [384, 384]
    max_target_enc_size: 16382  # maximum number of bytes to encode detection targets into pickle
